-- ========================================================
-- AIRLINE RESERVATION SYSTEM - OVERALL PROJECT QUERIES
-- Database Name: airline_reservation
-- ========================================================

USE airline_reservation;

-- ========================================================
-- SECTION 1: BASIC RETRIEVAL QUERIES
-- ========================================================

-- 1. Display all airlines
SELECT * FROM airline;

-- 2. Show all flights
SELECT * FROM flight;

-- 3. Display all passengers
SELECT * FROM passenger;

-- 4. Find flights from Hyderabad to Delhi
SELECT * FROM flight 
WHERE source = 'Hyderabad' AND destination = 'Delhi';

-- 5. Display available seats
SELECT * FROM seat 
WHERE availability = 'Available';

-- 6. Show all confirmed bookings
SELECT * FROM booking 
WHERE booking_status = 'Confirmed';

-- 7. Display all pilots
SELECT * FROM pilot;

-- 8. Find passengers travelling in Business Class
SELECT DISTINCT p.* 
FROM passenger p 
JOIN booking b ON p.passenger_id = b.passenger_id 
JOIN seat s ON b.flight_id = s.flight_id 
WHERE s.class_type = 'Business';

-- 9. Display all online payments
SELECT * FROM payment 
WHERE payment_mode = 'Online';

-- 10. Find baggage weighing more than 20 kg
SELECT * FROM baggage 
WHERE weight > 20.00;


-- ========================================================
-- SECTION 2: AGGREGATION AND GROUPING QUERIES
-- ========================================================

-- 11. Count flights operated by each airline
SELECT a.airline_name, COUNT(f.flight_id) AS flight_count 
FROM airline a 
LEFT JOIN flight f ON a.airline_id = f.airline_id 
GROUP BY a.airline_id, a.airline_name;

-- 12. Display passenger count for each flight
SELECT f.flight_id, f.source, f.destination, COUNT(b.passenger_id) AS passenger_count 
FROM flight f 
LEFT JOIN booking b ON f.flight_id = b.flight_id 
GROUP BY f.flight_id;

-- 13. Find the average ticket price
SELECT AVG(ticket_price) AS avg_ticket_price 
FROM booking;

-- 14. Display pilot-wise flight count
SELECT p.pilot_name, COUNT(f.flight_id) AS flight_count 
FROM pilot p 
LEFT JOIN flight f ON p.pilot_id = f.pilot_id 
GROUP BY p.pilot_id, p.pilot_name;

-- 15. Find the airline operating the maximum flights
SELECT a.airline_name, COUNT(f.flight_id) AS flight_count 
FROM airline a 
JOIN flight f ON a.airline_id = f.airline_id 
GROUP BY a.airline_id, a.airline_name 
ORDER BY flight_count DESC 
LIMIT 1;

-- 16. Count available seats in each flight
SELECT flight_id, COUNT(*) AS available_seats 
FROM seat 
WHERE availability = 'Available' 
GROUP BY flight_id;

-- 17. Display total revenue generated by each airline
SELECT a.airline_name, SUM(b.ticket_price) AS total_revenue 
FROM airline a 
JOIN flight f ON a.airline_id = f.airline_id 
JOIN booking b ON f.flight_id = b.flight_id 
WHERE b.booking_status = 'Confirmed' 
GROUP BY a.airline_id, a.airline_name;

-- 18. Find passengers with more than three bookings
SELECT p.*, COUNT(b.booking_id) AS booking_count 
FROM passenger p 
JOIN booking b ON p.passenger_id = b.passenger_id 
GROUP BY p.passenger_id 
HAVING COUNT(b.booking_id) > 3;

-- 19. Display average baggage weight per flight
SELECT f.flight_id, AVG(bg.weight) AS avg_baggage_weight 
FROM flight f 
JOIN booking b ON f.flight_id = b.flight_id 
JOIN baggage bg ON b.booking_id = bg.booking_id 
GROUP BY f.flight_id;

-- 20. Find the top 5 costliest tickets
SELECT * FROM booking 
ORDER BY ticket_price DESC 
LIMIT 5;


-- ========================================================
-- SECTION 3: ADVANCED JOIN AND SUBQUERY QUERIES
-- ========================================================

-- 21. Display passenger names with flight details
SELECT p.name AS passenger_name, f.* 
FROM passenger p 
JOIN booking b ON p.passenger_id = b.passenger_id 
JOIN flight f ON b.flight_id = f.flight_id;

-- 22. Show booking details with payment status
SELECT b.*, p.payment_status 
FROM booking b 
LEFT JOIN payment p ON b.booking_id = p.booking_id;

-- 23. Display airline name with flight schedule
SELECT a.airline_name, f.flight_id, f.source, f.destination, f.departure_time, f.arrival_time 
FROM airline a 
JOIN flight f ON a.airline_id = f.airline_id;

-- 24. Find passengers who never booked a flight
SELECT * FROM passenger 
WHERE passenger_id NOT IN (SELECT passenger_id FROM booking);

-- 25. Find flights with no bookings
SELECT * FROM flight 
WHERE flight_id NOT IN (SELECT flight_id FROM booking);

-- 26. Display the most travelled route
SELECT source, destination, COUNT(*) AS route_count 
FROM flight f 
JOIN booking b ON f.flight_id = b.flight_id 
WHERE b.booking_status = 'Confirmed' 
GROUP BY source, destination 
ORDER BY route_count DESC 
LIMIT 1;

-- 27. Find the airline generating the highest revenue
SELECT a.airline_name, SUM(b.ticket_price) AS total_revenue 
FROM airline a 
JOIN flight f ON a.airline_id = f.airline_id 
JOIN booking b ON f.flight_id = b.flight_id 
WHERE b.booking_status = 'Confirmed' 
GROUP BY a.airline_id, a.airline_name 
ORDER BY total_revenue DESC 
LIMIT 1;

-- 28. Display passengers paying baggage fees above ₹2,000
SELECT DISTINCT p.*, bg.baggage_fee 
FROM passenger p 
JOIN booking b ON p.passenger_id = b.passenger_id 
JOIN baggage bg ON b.booking_id = bg.booking_id 
WHERE bg.baggage_fee > 2000.00;

-- 29. Find the pilot flying the maximum number of flights
SELECT p.pilot_name, COUNT(f.flight_id) AS flight_count 
FROM pilot p 
JOIN flight f ON p.pilot_id = f.pilot_id 
GROUP BY p.pilot_id, p.pilot_name 
ORDER BY flight_count DESC 
LIMIT 1;

-- 30. Display flight-wise total ticket revenue
SELECT f.flight_id, SUM(b.ticket_price) AS total_revenue 
FROM flight f 
JOIN booking b ON f.flight_id = b.flight_id 
WHERE b.booking_status = 'Confirmed' 
GROUP BY f.flight_id;